### PR TITLE
Makefile fix: grep on localized strings

### PR DESCRIPTION
**Pull request by asaintsever**
Little PR to fix an issue with "non-English git" installs

### CODE REVIEW

**Comment by asaintsever** [comment]
Some targets are not part of the `.PHONY` but this does not seem to trigger any issues. Let me know if you want me to add the missing targets.

**Comment by isaaguilar** [comment]
@asaintsever  I didn't even think about this. Hm...  there is some concern from a personal workflow since my git repo sometimes has files I have in the directory but don't add to the stage. This means `wc -l` will almost always be > 0 in my case. 

How about this one-liner:

```bash
git ls-remote .|grep $(git rev-parse HEAD).*tags|head -n1|sed "s/^.*\///"
```

It's almost the same as my original with acceptable differences.

**Comment by asaintsever** [comment]
Looks good

**Comment by isaaguilar** [comment]
Should not need the enclosing if statement. The git command will return nothing if grep produces no results.

**Comment by asaintsever** [comment]
Oups right

**Comment by isaaguilar** [comment]
Thanks for the quick updates. 👍

**Pull request merged**
